package spsu.edu.financial.model;

// Generated Nov 15, 2013 5:46:12 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ExpenseDetails generated by hbm2java
 */
public class ExpenseDetails implements java.io.Serializable {

	private int expenseId;
	private Integer projectId;
	private Integer resourceId;
	private BigDecimal hoursWorked;
	private BigDecimal expenses;
	private Date referenceDate;
	private String referenceDocumentation;
	private Date weekNumber;

	public ExpenseDetails() {
	}

	public ExpenseDetails(int expenseId) {
		this.expenseId = expenseId;
	}

	public ExpenseDetails(int expenseId, Integer projectId, Integer resourceId,
			BigDecimal hoursWorked, BigDecimal expenses, Date referenceDate,
			String referenceDocumentation, Date weekNumber) {
		this.expenseId = expenseId;
		this.projectId = projectId;
		this.resourceId = resourceId;
		this.hoursWorked = hoursWorked;
		this.expenses = expenses;
		this.referenceDate = referenceDate;
		this.referenceDocumentation = referenceDocumentation;
		this.weekNumber = weekNumber;
	}

	public int getExpenseId() {
		return this.expenseId;
	}

	public void setExpenseId(int expenseId) {
		this.expenseId = expenseId;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public BigDecimal getHoursWorked() {
		return this.hoursWorked;
	}

	public void setHoursWorked(BigDecimal hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

	public BigDecimal getExpenses() {
		return this.expenses;
	}

	public void setExpenses(BigDecimal expenses) {
		this.expenses = expenses;
	}

	public Date getReferenceDate() {
		return this.referenceDate;
	}

	public void setReferenceDate(Date referenceDate) {
		this.referenceDate = referenceDate;
	}

	public String getReferenceDocumentation() {
		return this.referenceDocumentation;
	}

	public void setReferenceDocumentation(String referenceDocumentation) {
		this.referenceDocumentation = referenceDocumentation;
	}

	public Date getWeekNumber() {
		return this.weekNumber;
	}

	public void setWeekNumber(Date weekNumber) {
		this.weekNumber = weekNumber;
	}

}
