package spsu.edu.financial.model;

// Generated Nov 16, 2013 10:00:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Resources generated by hbm2java
 */
public class Resources implements java.io.Serializable {

	private Integer resourceId;
	private String category;
	private String description;
	private String auditCreateUser;
	private Date auditCreateDatetime;
	private String auditUpdateUser;
	private Date auditUpdateDatetime;

	public Resources() {
	}

	public Resources(String category) {
		this.category = category;
	}

	public Resources(String category, String description,
			String auditCreateUser, Date auditCreateDatetime,
			String auditUpdateUser, Date auditUpdateDatetime) {
		this.category = category;
		this.description = description;
		this.auditCreateUser = auditCreateUser;
		this.auditCreateDatetime = auditCreateDatetime;
		this.auditUpdateUser = auditUpdateUser;
		this.auditUpdateDatetime = auditUpdateDatetime;
	}

	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAuditCreateUser() {
		return this.auditCreateUser;
	}

	public void setAuditCreateUser(String auditCreateUser) {
		this.auditCreateUser = auditCreateUser;
	}

	public Date getAuditCreateDatetime() {
		return this.auditCreateDatetime;
	}

	public void setAuditCreateDatetime(Date auditCreateDatetime) {
		this.auditCreateDatetime = auditCreateDatetime;
	}

	public String getAuditUpdateUser() {
		return this.auditUpdateUser;
	}

	public void setAuditUpdateUser(String auditUpdateUser) {
		this.auditUpdateUser = auditUpdateUser;
	}

	public Date getAuditUpdateDatetime() {
		return this.auditUpdateDatetime;
	}

	public void setAuditUpdateDatetime(Date auditUpdateDatetime) {
		this.auditUpdateDatetime = auditUpdateDatetime;
	}

}
