package spsu.edu.financial.model;

// Generated Nov 16, 2013 10:00:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import framework.model.BaseObject;

/**
 * ExpenseDetails generated by hbm2java
 */
public class ExpenseDetails  extends BaseObject {
	private static final long serialVersionUID = 7157870854160664719L;
	
	private Integer expenseId;
	private Integer projectId;
	private Integer resourceId;
	private BigDecimal hoursWorked;
	private BigDecimal expenses;
	private Date referenceDate;
	private String referenceDocumentation;
	private Integer weekNumber;
	
	private Projects project;
	private Resources resource;


	public Integer getExpenseId() {
		return expenseId;
	}

	public void setExpenseId(Integer expenseId) {
		this.expenseId = expenseId;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	public BigDecimal getHoursWorked() {
		return this.hoursWorked;
	}

	public void setHoursWorked(BigDecimal hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

	public BigDecimal getExpenses() {
		return this.expenses;
	}

	public void setExpenses(BigDecimal expenses) {
		this.expenses = expenses;
	}

	public Date getReferenceDate() {
		return this.referenceDate;
	}

	public void setReferenceDate(Date referenceDate) {
		this.referenceDate = referenceDate;
	}

	public String getReferenceDocumentation() {
		return this.referenceDocumentation;
	}

	public void setReferenceDocumentation(String referenceDocumentation) {
		this.referenceDocumentation = referenceDocumentation;
	}

	public Integer getWeekNumber() {
		return this.weekNumber;
	}

	public void setWeekNumber(Integer weekNumber) {
		this.weekNumber = weekNumber;
	}

	@Override
	protected Long getPk() {
		// TODO Auto-generated method stub
		return null;
	}

	public Projects getProject() {
		return project;
	}

	public void setProject(Projects project) {
		this.project = project;
	}

	public Resources getResource() {
		return resource;
	}

	public void setResource(Resources resource) {
		this.resource = resource;
	}

}
