package spsu.edu.financial.model;

// Generated Nov 15, 2013 11:54:57 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import framework.model.BaseObject;

/**
 * Projects generated by hbm2java
 */
public class Projects extends BaseObject {
	private static final long serialVersionUID = 6032056250764705705L;
	
	private Integer projectId;
	private String projectName;
	private String description;
	private String status;
	private Date startDate;
	private Date endDate;
	private BigDecimal projectedCost;
	private BigDecimal actualCost;
	private String comments;
	private String clientName;
	private String clientEmail;
	private String managerId;
	private Users finUser;


	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getProjectedCost() {
		return this.projectedCost;
	}

	public void setProjectedCost(BigDecimal projectedCost) {
		this.projectedCost = projectedCost;
	}

	public BigDecimal getActualCost() {
		return this.actualCost;
	}

	public void setActualCost(BigDecimal actualCost) {
		this.actualCost = actualCost;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getClientEmail() {
		return this.clientEmail;
	}

	public void setClientEmail(String clientEmail) {
		this.clientEmail = clientEmail;
	}

	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Override
	protected Long getPk() {
		// TODO Auto-generated method stub
		return null;
	}

	public Users getFinUser() {
		return finUser;
	}

	public void setFinUser(Users finUser) {
		this.finUser = finUser;
	}

	public String getIdString(){
		return String.valueOf(projectId);
	}
}
