package spsu.edu.financial.model;

// Generated Nov 10, 2013 7:28:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userId;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String role;
	private String auditCreateUser;
	private Date auditCeateDatetime;
	private String auditUpdateUser;
	private Date auditUpdateDatetime;

	public Users() {
	}

	public Users(String userId, String firstName, String lastName) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Users(String userId, String firstName, String lastName,
			String email, String password, String role, String auditCreateUser,
			Date auditCeateDatetime, String auditUpdateUser,
			Date auditUpdateDatetime) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.role = role;
		this.auditCreateUser = auditCreateUser;
		this.auditCeateDatetime = auditCeateDatetime;
		this.auditUpdateUser = auditUpdateUser;
		this.auditUpdateDatetime = auditUpdateDatetime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getAuditCreateUser() {
		return this.auditCreateUser;
	}

	public void setAuditCreateUser(String auditCreateUser) {
		this.auditCreateUser = auditCreateUser;
	}

	public Date getAuditCeateDatetime() {
		return this.auditCeateDatetime;
	}

	public void setAuditCeateDatetime(Date auditCeateDatetime) {
		this.auditCeateDatetime = auditCeateDatetime;
	}

	public String getAuditUpdateUser() {
		return this.auditUpdateUser;
	}

	public void setAuditUpdateUser(String auditUpdateUser) {
		this.auditUpdateUser = auditUpdateUser;
	}

	public Date getAuditUpdateDatetime() {
		return this.auditUpdateDatetime;
	}

	public void setAuditUpdateDatetime(Date auditUpdateDatetime) {
		this.auditUpdateDatetime = auditUpdateDatetime;
	}

}
